/**
 * P6 任务集：每个任务 = 一段客户的自然语言需求 + 隐藏的结构化标准（判定用）。
 * 判定只看玩家返回的 TravelPlan，用产品库独立核算（见 judge.ts）。
 */
import type { ProjectTask } from '../types'
import type { TravelEnv } from './env/index'
import { checkTravel, type TravelPlan, type TripSpec } from './judge'

export interface TravelTask extends TripSpec {
  id: string
  title: string
  core: boolean
  request: string
}

const t = (x: TravelTask) => x

export const TRAVEL_TASKS: TravelTask[] = [
  // ———————————— 核心任务（模拟模型可解，参与评星） ————————————
  t({
    id: 'cd-sichuan',
    title: '成都 3 天：川菜 + 火锅 + 预算',
    core: true,
    request: '我和女朋友两个人，11 月 6 日从上海出发去成都玩 3 天，11 月 8 日回上海。总预算 6000 元，想吃正宗川菜，也一定要吃一次火锅。',
    origin: '上海',
    stops: [{ city: '成都', days: 3 }],
    startDate: '2026-11-06',
    people: 2,
    budget: 6000,
    prefs: { cuisines: ['川菜', '火锅'] },
    feasible: true,
  }),
  t({
    id: 'xa-rail-closure',
    title: '西安 3 天：不坐飞机 + 周一闭馆',
    core: true,
    request: '11 月 9 日到 11 日，我们 2 个人从上海去西安玩三天，11 日回上海。我们不坐飞机，只坐高铁；每天最多逛 2 个景点，不想太累。预算 5000 元。',
    origin: '上海',
    stops: [{ city: '西安', days: 3 }],
    startDate: '2026-11-09',
    people: 2,
    budget: 5000,
    prefs: { noFlight: true, maxAttractionsPerDay: 2 },
    feasible: true,
  }),
  t({
    id: 'hz-pet',
    title: '杭州周末：带狗 + 最少入住晚数',
    core: true,
    request: '这个周末（11 月 14 日—15 日）我们两口子想带着家里的柯基从上海去杭州玩两天，住一晚，15 号回上海。预算 1500 元以内。',
    origin: '上海',
    stops: [{ city: '杭州', days: 2 }],
    startDate: '2026-11-14',
    people: 2,
    budget: 1500,
    prefs: { pets: true },
    feasible: true,
  }),
  t({
    id: 'xm-accessible',
    title: '厦门 3 天：轮椅无障碍 + 3 人',
    core: true,
    request: '11 月 20 日到 22 日，我陪爸妈从广州去厦门玩 3 天，一共 3 个人，22 日回广州。我爸坐轮椅，酒店和景点都必须有无障碍设施。预算 5000 元。',
    origin: '广州',
    stops: [{ city: '厦门', days: 3 }],
    startDate: '2026-11-20',
    people: 3,
    budget: 5000,
    prefs: { accessible: true },
    feasible: true,
  }),
  t({
    id: 'bj-family',
    title: '北京 4 天：一家四口 + 周一闭馆',
    core: true,
    request: '我们一家四口 11 月 16 日从上海出发去北京，玩 4 天，19 日回上海。预算 12000 元。',
    origin: '上海',
    stops: [{ city: '北京', days: 4 }],
    startDate: '2026-11-16',
    people: 4,
    budget: 12000,
    prefs: {},
    feasible: true,
  }),
  t({
    id: 'gz-cantonese',
    title: '广州 2 天：粤菜 + 营业时间',
    core: true,
    request: '11 月 21 日、22 日两天，我和同事 2 个人从上海去广州玩，22 日晚上前回上海。想吃地道粤菜。预算 3800 元。',
    origin: '上海',
    stops: [{ city: '广州', days: 2 }],
    startDate: '2026-11-21',
    people: 2,
    budget: 3800,
    prefs: { cuisines: ['粤菜'] },
    feasible: true,
  }),
  t({
    id: 'cq-low-budget',
    title: '预算不可能满足',
    core: true,
    request: '11 月 27 日到 29 日，两个人从北京去重庆玩 3 天，29 日回北京。总预算 1500 元，吃住行门票都算在内。',
    origin: '北京',
    stops: [{ city: '重庆', days: 3 }],
    startDate: '2026-11-27',
    people: 2,
    budget: 1500,
    prefs: {},
    feasible: false,
    infeasibleWords: ['预算'],
    infeasibleWhy: '两人往返北京—重庆最便宜的交通就要 2740 元，已经超出 1500 元的预算',
  }),
  t({
    id: 'xa-cd-two-city',
    title: '两城联游：西安 → 成都，全程高铁',
    core: true,
    request: '我一个人，11 月 12 日从北京出发，先在西安玩 2 天，再去成都玩 2 天，15 日从成都回北京。全程不坐飞机。预算 5000 元。',
    origin: '北京',
    stops: [
      { city: '西安', days: 2 },
      { city: '成都', days: 2 },
    ],
    startDate: '2026-11-12',
    people: 1,
    budget: 5000,
    prefs: { noFlight: true },
    feasible: true,
  }),

  // ———————————— 完整任务集（真实模型基准） ————————————
  t({
    id: 'hz-student',
    title: '杭州 2 天：学生穷游',
    core: false,
    request: '11 月 7 日一个人从上海去杭州玩两天，8 日回上海。学生党，预算 700 元。',
    origin: '上海',
    stops: [{ city: '杭州', days: 2 }],
    startDate: '2026-11-07',
    people: 1,
    budget: 700,
    prefs: {},
    feasible: true,
  }),
  t({
    id: 'cd-pet-overnight',
    title: '带猫去成都只住一晚（不可行）',
    core: false,
    request: '11 月 13 日、14 日，我们 2 个人带着猫从上海去成都玩两天，只住一晚，14 日回上海。预算 8000 元。',
    origin: '上海',
    stops: [{ city: '成都', days: 2 }],
    startDate: '2026-11-13',
    people: 2,
    budget: 8000,
    prefs: { pets: true },
    feasible: false,
    infeasibleWords: ['宠物', '连住', '入住', '酒店'],
    infeasibleWhy: '成都可以带宠物的酒店都要求至少连住 2 晚，而行程只住 1 晚',
  }),
  t({
    id: 'bj-xm-no-flight',
    title: '北京去厦门不坐飞机（不可行）',
    core: false,
    request: '11 月 20 日到 22 日，我们 2 个人从北京去厦门玩 3 天，22 日回北京。我恐高，绝对不坐飞机。预算 10000 元。',
    origin: '北京',
    stops: [{ city: '厦门', days: 3 }],
    startDate: '2026-11-20',
    people: 2,
    budget: 10000,
    prefs: { noFlight: true },
    feasible: false,
    infeasibleWords: ['飞机', '高铁', '火车', '交通', '航班'],
    infeasibleWhy: '北京和厦门之间只有航班，没有高铁',
  }),
  t({
    id: 'cq-hotpot',
    title: '重庆 3 天：火锅 + 每天最多 2 个景点',
    core: false,
    request: '11 月 6 日到 8 日，2 个人从上海去重庆，8 日回上海。来重庆必须吃火锅！每天最多 2 个景点，慢慢逛。预算 6000 元。',
    origin: '上海',
    stops: [{ city: '重庆', days: 3 }],
    startDate: '2026-11-06',
    people: 2,
    budget: 6000,
    prefs: { cuisines: ['火锅'], maxAttractionsPerDay: 2 },
    feasible: true,
  }),
  t({
    id: 'bj-accessible',
    title: '北京 3 天：无障碍',
    core: false,
    request: '11 月 21 日到 23 日，我推着坐轮椅的妈妈从上海去北京玩 3 天，一共 2 个人，23 日回上海。住的和玩的都要有无障碍设施。预算 6000 元。',
    origin: '上海',
    stops: [{ city: '北京', days: 3 }],
    startDate: '2026-11-21',
    people: 2,
    budget: 6000,
    prefs: { accessible: true },
    feasible: true,
  }),
  t({
    id: 'xa-solo-4',
    title: '西安 4 天：独自深度游',
    core: false,
    request: '我想一个人从北京去西安待 4 天，11 月 2 日出发，5 日回北京。预算 2500 元。',
    origin: '北京',
    stops: [{ city: '西安', days: 4 }],
    startDate: '2026-11-02',
    people: 1,
    budget: 2500,
    prefs: {},
    feasible: true,
  }),
  t({
    id: 'gz-family-room',
    title: '广州 3 天：三口之家住家庭房',
    core: false,
    request: '11 月 13 日到 15 日，我们三口之家从北京去广州玩 3 天，15 日回北京。只住家庭房，一家人住一间。预算 9000 元。',
    origin: '北京',
    stops: [{ city: '广州', days: 3 }],
    startDate: '2026-11-13',
    people: 3,
    budget: 9000,
    prefs: { roomType: '家庭房' },
    feasible: true,
  }),
  t({
    id: 'cd-cq',
    title: '两城联游：成都 → 重庆',
    core: false,
    request: '11 月 19 日从上海出发，2 个人，先成都 2 天，再重庆 2 天，22 日从重庆回上海。火锅和川菜都要吃到。预算 8000 元。',
    origin: '上海',
    stops: [
      { city: '成都', days: 2 },
      { city: '重庆', days: 2 },
    ],
    startDate: '2026-11-19',
    people: 2,
    budget: 8000,
    prefs: { cuisines: ['火锅', '川菜'] },
    feasible: true,
  }),
  t({
    id: 'hz-xm',
    title: '两城联游：杭州 → 厦门',
    core: false,
    request: '11 月 26 日从上海出发，我们 2 个人先去杭州玩 2 天，然后去厦门玩 2 天，29 日从厦门回上海。预算 7000 元。',
    origin: '上海',
    stops: [
      { city: '杭州', days: 2 },
      { city: '厦门', days: 2 },
    ],
    startDate: '2026-11-26',
    people: 2,
    budget: 7000,
    prefs: {},
    feasible: true,
  }),
  t({
    id: 'bj-veg',
    title: '北京 3 天：素食',
    core: false,
    request: '11 月 5 日到 7 日，2 个人从上海去北京，7 日回上海。我们想尝尝北京的素菜，行程里至少安排一顿素食餐厅。预算 7000 元。',
    origin: '上海',
    stops: [{ city: '北京', days: 3 }],
    startDate: '2026-11-05',
    people: 2,
    budget: 7000,
    prefs: { cuisines: ['素食'] },
    feasible: true,
  }),
  t({
    id: 'sh-benbang',
    title: '上海 3 天：4 人 + 本帮菜',
    core: false,
    request: '11 月 12 日到 14 日，我们 4 个朋友从北京去上海玩 3 天，14 日回北京。想吃本帮菜。预算 10000 元。',
    origin: '北京',
    stops: [{ city: '上海', days: 3 }],
    startDate: '2026-11-12',
    people: 4,
    budget: 10000,
    prefs: { cuisines: ['本帮菜'] },
    feasible: true,
  }),
  t({
    id: 'gz-cq-solo',
    title: '重庆 2 天：精打细算',
    core: false,
    request: '11 月 23 日、24 日，我一个人从广州去重庆，24 日回广州。预算只有 1500 元。',
    origin: '广州',
    stops: [{ city: '重庆', days: 2 }],
    startDate: '2026-11-23',
    people: 1,
    budget: 1500,
    prefs: {},
    feasible: true,
  }),
  t({
    id: 'xm-pet',
    title: '厦门 3 天：带狗看海',
    core: false,
    request: '11 月 27 日到 29 日，我们 2 个人带着狗从上海去厦门玩 3 天，29 日回上海。预算 5000 元。',
    origin: '上海',
    stops: [{ city: '厦门', days: 3 }],
    startDate: '2026-11-27',
    people: 2,
    budget: 5000,
    prefs: { pets: true },
    feasible: true,
  }),
  t({
    id: 'cd-slow',
    title: '成都 4 天：每天一个景点 + 川菜素食',
    core: false,
    request: '11 月 8 日到 11 日，2 个人从北京去成都，11 日回北京。节奏放慢，每天最多 1 个景点。想吃川菜，也想吃一次素斋。预算 9000 元。',
    origin: '北京',
    stops: [{ city: '成都', days: 4 }],
    startDate: '2026-11-08',
    people: 2,
    budget: 9000,
    prefs: { maxAttractionsPerDay: 1, cuisines: ['川菜', '素食'] },
    feasible: true,
  }),
  t({
    id: 'gz-low-budget',
    title: '四人去广州预算太低（不可行）',
    core: false,
    request: '11 月 6 日到 8 日，我们 4 个人从北京去广州玩 3 天，8 日回北京。预算 3000 元。',
    origin: '北京',
    stops: [{ city: '广州', days: 3 }],
    startDate: '2026-11-06',
    people: 4,
    budget: 3000,
    prefs: {},
    feasible: false,
    infeasibleWords: ['预算'],
    infeasibleWhy: '4 人往返北京—广州最便宜的交通就要 6896 元，远超 3000 元的预算',
  }),
  t({
    id: 'hz-accessible-family',
    title: '杭州 3 天：4 人 + 无障碍',
    core: false,
    request: '11 月 18 日到 20 日，我们一家 4 口从北京去杭州，20 日回北京。奶奶坐轮椅，酒店和景点都要无障碍。预算 9000 元。',
    origin: '北京',
    stops: [{ city: '杭州', days: 3 }],
    startDate: '2026-11-18',
    people: 4,
    budget: 9000,
    prefs: { accessible: true },
    feasible: true,
  }),
]

export function toTasks(): ProjectTask<TravelEnv, TravelPlan>[] {
  return TRAVEL_TASKS.map((spec) => ({
    id: spec.id,
    title: spec.title,
    core: spec.core,
    input: spec.request,
    check: ({ output }) => checkTravel(spec, output),
  }))
}
