/**
 * P6 任务集：每个任务 = 一段客户的自然语言需求 + 隐藏的结构化标准（判定用）。
 * 判定只看玩家返回的 TravelPlan，用产品库独立核算（见 judge.ts）。
 */
import { L } from '../../engine/locale'
import type { ProjectTask } from '../types'
import type { TravelEnv } from './env/index'
import { checkTravel, type TravelPlan, type TripSpec } from './judge'

export interface TravelTask extends TripSpec {
  id: string
  title: string
  core: boolean
  request: string
}

const t = (x: TravelTask) => x

export const TRAVEL_TASKS: TravelTask[] = [
  // ———————————— 核心任务（模拟模型可解，参与评星） ————————————
  t({
    id: 'cd-sichuan',
    title: L('成都 3 天：川菜 + 火锅 + 预算', 'Chengdu, 3 days: Sichuan food + hotpot + budget'),
    core: true,
    request: L(
      '我和女朋友两个人，11 月 6 日从上海出发去成都玩 3 天，11 月 8 日回上海。总预算 6000 元，想吃正宗川菜，也一定要吃一次火锅。',
      'My girlfriend and I (2 people) are leaving Shanghai on November 6 for 3 days in Chengdu, back to Shanghai on November 8. Total budget ¥6000. We want authentic Sichuan food, and we have to have hotpot at least once.',
    ),
    origin: L('上海', 'Shanghai'),
    stops: [{ city: L('成都', 'Chengdu'), days: 3 }],
    startDate: '2026-11-06',
    people: 2,
    budget: 6000,
    prefs: { cuisines: L(['川菜', '火锅'], ['Sichuan', 'hotpot']) },
    feasible: true,
  }),
  t({
    id: 'xa-rail-closure',
    title: L('西安 3 天：不坐飞机 + 周一闭馆', "Xi'an, 3 days: no flights + closed on Mondays"),
    core: true,
    request: L(
      '11 月 9 日到 11 日，我们 2 个人从上海去西安玩三天，11 日回上海。我们不坐飞机，只坐高铁；每天最多逛 2 个景点，不想太累。预算 5000 元。',
      "November 9 to 11, two of us are going from Shanghai to Xi'an for three days, back to Shanghai on the 11th. We don't fly, trains only, and at most 2 attractions a day, we don't want to get worn out. Budget ¥5000.",
    ),
    origin: L('上海', 'Shanghai'),
    stops: [{ city: L('西安', "Xi'an"), days: 3 }],
    startDate: '2026-11-09',
    people: 2,
    budget: 5000,
    prefs: { noFlight: true, maxAttractionsPerDay: 2 },
    feasible: true,
  }),
  t({
    id: 'hz-pet',
    title: L('杭州周末：带狗 + 最少入住晚数', 'Hangzhou weekend: bringing the dog + minimum stay'),
    core: true,
    request: L(
      '这个周末（11 月 14 日—15 日）我们两口子想带着家里的柯基从上海去杭州玩两天，住一晚，15 号回上海。预算 1500 元以内。',
      'This weekend (November 14-15) my partner and I want to take our corgi from Shanghai to Hangzhou for two days, one night, back to Shanghai on the 15th. Budget under ¥1500.',
    ),
    origin: L('上海', 'Shanghai'),
    stops: [{ city: L('杭州', 'Hangzhou'), days: 2 }],
    startDate: '2026-11-14',
    people: 2,
    budget: 1500,
    prefs: { pets: true },
    feasible: true,
  }),
  t({
    id: 'xm-accessible',
    title: L('厦门 3 天：轮椅无障碍 + 3 人', 'Xiamen, 3 days: wheelchair access + 3 people'),
    core: true,
    request: L(
      '11 月 20 日到 22 日，我陪爸妈从广州去厦门玩 3 天，一共 3 个人，22 日回广州。我爸坐轮椅，酒店和景点都必须有无障碍设施。预算 5000 元。',
      "November 20 to 22, I'm taking my parents from Guangzhou to Xiamen for 3 days, 3 people in total, back to Guangzhou on the 22nd. My dad uses a wheelchair, so the hotel and every attraction must be wheelchair accessible. Budget ¥5000.",
    ),
    origin: L('广州', 'Guangzhou'),
    stops: [{ city: L('厦门', 'Xiamen'), days: 3 }],
    startDate: '2026-11-20',
    people: 3,
    budget: 5000,
    prefs: { accessible: true },
    feasible: true,
  }),
  t({
    id: 'bj-family',
    title: L('北京 4 天：一家四口 + 周一闭馆', 'Beijing, 4 days: family of four + closed on Mondays'),
    core: true,
    request: L(
      '我们一家四口 11 月 16 日从上海出发去北京，玩 4 天，19 日回上海。预算 12000 元。',
      'Our family of four is leaving Shanghai for Beijing on November 16 for 4 days, back to Shanghai on the 19th. Budget ¥12000.',
    ),
    origin: L('上海', 'Shanghai'),
    stops: [{ city: L('北京', 'Beijing'), days: 4 }],
    startDate: '2026-11-16',
    people: 4,
    budget: 12000,
    prefs: {},
    feasible: true,
  }),
  t({
    id: 'gz-cantonese',
    title: L('广州 2 天：粤菜 + 营业时间', 'Guangzhou, 2 days: Cantonese food + opening hours'),
    core: true,
    request: L(
      '11 月 21 日、22 日两天，我和同事 2 个人从上海去广州玩，22 日晚上前回上海。想吃地道粤菜。预算 3800 元。',
      'On November 21 and 22, a coworker and I (2 people) are going from Shanghai to Guangzhou, back in Shanghai by the evening of the 22nd. We want proper Cantonese food. Budget ¥3800.',
    ),
    origin: L('上海', 'Shanghai'),
    stops: [{ city: L('广州', 'Guangzhou'), days: 2 }],
    startDate: '2026-11-21',
    people: 2,
    budget: 3800,
    prefs: { cuisines: L(['粤菜'], ['Cantonese']) },
    feasible: true,
  }),
  t({
    id: 'cq-low-budget',
    title: L('预算不可能满足', 'Budget that can never work'),
    core: true,
    request: L(
      '11 月 27 日到 29 日，两个人从北京去重庆玩 3 天，29 日回北京。总预算 1500 元，吃住行门票都算在内。',
      'November 27 to 29, two people from Beijing to Chongqing for 3 days, back to Beijing on the 29th. Total budget ¥1500, covering transport, hotels, food and tickets.',
    ),
    origin: L('北京', 'Beijing'),
    stops: [{ city: L('重庆', 'Chongqing'), days: 3 }],
    startDate: '2026-11-27',
    people: 2,
    budget: 1500,
    prefs: {},
    feasible: false,
    infeasibleWords: L(['预算'], ['budget']),
    infeasibleWhy: L('两人往返北京—重庆最便宜的交通就要 2740 元，已经超出 1500 元的预算', 'the cheapest round trip Beijing–Chongqing for two already costs ¥2740, more than the ¥1500 budget'),
  }),
  t({
    id: 'xa-cd-two-city',
    title: L('两城联游：西安 → 成都，全程高铁', "Two cities: Xi'an → Chengdu, by train only"),
    core: true,
    request: L(
      '我一个人，11 月 12 日从北京出发，先在西安玩 2 天，再去成都玩 2 天，15 日从成都回北京。全程不坐飞机。预算 5000 元。',
      "Just me, leaving Beijing on November 12: 2 days in Xi'an first, then 2 days in Chengdu, back to Beijing from Chengdu on the 15th. No flights for the whole trip. Budget ¥5000.",
    ),
    origin: L('北京', 'Beijing'),
    stops: [
      { city: L('西安', "Xi'an"), days: 2 },
      { city: L('成都', 'Chengdu'), days: 2 },
    ],
    startDate: '2026-11-12',
    people: 1,
    budget: 5000,
    prefs: { noFlight: true },
    feasible: true,
  }),

  // ———————————— 完整任务集（真实模型基准） ————————————
  t({
    id: 'hz-student',
    title: L('杭州 2 天：学生穷游', 'Hangzhou, 2 days: student on a shoestring'),
    core: false,
    request: L(
      '11 月 7 日一个人从上海去杭州玩两天，8 日回上海。学生党，预算 700 元。',
      "November 7, just me, Shanghai to Hangzhou for two days, back to Shanghai on the 8th. I'm a student, budget ¥700.",
    ),
    origin: L('上海', 'Shanghai'),
    stops: [{ city: L('杭州', 'Hangzhou'), days: 2 }],
    startDate: '2026-11-07',
    people: 1,
    budget: 700,
    prefs: {},
    feasible: true,
  }),
  t({
    id: 'cd-pet-overnight',
    title: L('带猫去成都只住一晚（不可行）', 'Chengdu with a cat for one night (infeasible)'),
    core: false,
    request: L(
      '11 月 13 日、14 日，我们 2 个人带着猫从上海去成都玩两天，只住一晚，14 日回上海。预算 8000 元。',
      'November 13 and 14, two of us are taking our cat from Shanghai to Chengdu for two days, just one night, back to Shanghai on the 14th. Budget ¥8000.',
    ),
    origin: L('上海', 'Shanghai'),
    stops: [{ city: L('成都', 'Chengdu'), days: 2 }],
    startDate: '2026-11-13',
    people: 2,
    budget: 8000,
    prefs: { pets: true },
    feasible: false,
    infeasibleWords: L(['宠物', '连住', '入住', '酒店'], ['pet', 'night', 'stay', 'hotel']),
    infeasibleWhy: L('成都可以带宠物的酒店都要求至少连住 2 晚，而行程只住 1 晚', 'every pet-friendly hotel in Chengdu has a minimum stay of 2 nights, but the trip has only 1 night'),
  }),
  t({
    id: 'bj-xm-no-flight',
    title: L('北京去厦门不坐飞机（不可行）', 'Beijing to Xiamen without flying (infeasible)'),
    core: false,
    request: L(
      '11 月 20 日到 22 日，我们 2 个人从北京去厦门玩 3 天，22 日回北京。我恐高，绝对不坐飞机。预算 10000 元。',
      "November 20 to 22, two of us from Beijing to Xiamen for 3 days, back to Beijing on the 22nd. I'm afraid of heights, absolutely no flights. Budget ¥10000.",
    ),
    origin: L('北京', 'Beijing'),
    stops: [{ city: L('厦门', 'Xiamen'), days: 3 }],
    startDate: '2026-11-20',
    people: 2,
    budget: 10000,
    prefs: { noFlight: true },
    feasible: false,
    infeasibleWords: L(['飞机', '高铁', '火车', '交通', '航班'], ['flight', 'fly', 'train', 'rail', 'transport']),
    infeasibleWhy: L('北京和厦门之间只有航班，没有高铁', 'there are only flights between Beijing and Xiamen, no trains'),
  }),
  t({
    id: 'cq-hotpot',
    title: L('重庆 3 天：火锅 + 每天最多 2 个景点', 'Chongqing, 3 days: hotpot + at most 2 attractions a day'),
    core: false,
    request: L(
      '11 月 6 日到 8 日，2 个人从上海去重庆，8 日回上海。来重庆必须吃火锅！每天最多 2 个景点，慢慢逛。预算 6000 元。',
      "November 6 to 8, 2 people from Shanghai to Chongqing, back to Shanghai on the 8th. You can't come to Chongqing without hotpot! At most 2 attractions a day, we like to take it slow. Budget ¥6000.",
    ),
    origin: L('上海', 'Shanghai'),
    stops: [{ city: L('重庆', 'Chongqing'), days: 3 }],
    startDate: '2026-11-06',
    people: 2,
    budget: 6000,
    prefs: { cuisines: L(['火锅'], ['hotpot']), maxAttractionsPerDay: 2 },
    feasible: true,
  }),
  t({
    id: 'bj-accessible',
    title: L('北京 3 天：无障碍', 'Beijing, 3 days: accessible'),
    core: false,
    request: L(
      '11 月 21 日到 23 日，我推着坐轮椅的妈妈从上海去北京玩 3 天，一共 2 个人，23 日回上海。住的和玩的都要有无障碍设施。预算 6000 元。',
      "November 21 to 23, I'm taking my mom, who uses a wheelchair, from Shanghai to Beijing for 3 days, 2 people in total, back to Shanghai on the 23rd. The hotel and the sights all need to be wheelchair accessible. Budget ¥6000.",
    ),
    origin: L('上海', 'Shanghai'),
    stops: [{ city: L('北京', 'Beijing'), days: 3 }],
    startDate: '2026-11-21',
    people: 2,
    budget: 6000,
    prefs: { accessible: true },
    feasible: true,
  }),
  t({
    id: 'xa-solo-4',
    title: L('西安 4 天：独自深度游', "Xi'an, 4 days: solo deep dive"),
    core: false,
    request: L(
      '我想一个人从北京去西安待 4 天，11 月 2 日出发，5 日回北京。预算 2500 元。',
      "I want to spend 4 days in Xi'an on my own, leaving Beijing on November 2 and back to Beijing on the 5th. Budget ¥2500.",
    ),
    origin: L('北京', 'Beijing'),
    stops: [{ city: L('西安', "Xi'an"), days: 4 }],
    startDate: '2026-11-02',
    people: 1,
    budget: 2500,
    prefs: {},
    feasible: true,
  }),
  t({
    id: 'gz-family-room',
    title: L('广州 3 天：三口之家住家庭房', 'Guangzhou, 3 days: family of three in a family room'),
    core: false,
    request: L(
      '11 月 13 日到 15 日，我们三口之家从北京去广州玩 3 天，15 日回北京。只住家庭房，一家人住一间。预算 9000 元。',
      'November 13 to 15, our family of three is going from Beijing to Guangzhou for 3 days, back to Beijing on the 15th. Family rooms only, all of us in one room. Budget ¥9000.',
    ),
    origin: L('北京', 'Beijing'),
    stops: [{ city: L('广州', 'Guangzhou'), days: 3 }],
    startDate: '2026-11-13',
    people: 3,
    budget: 9000,
    prefs: { roomType: L('家庭房', 'family room') },
    feasible: true,
  }),
  t({
    id: 'cd-cq',
    title: L('两城联游：成都 → 重庆', 'Two cities: Chengdu → Chongqing'),
    core: false,
    request: L(
      '11 月 19 日从上海出发，2 个人，先成都 2 天，再重庆 2 天，22 日从重庆回上海。火锅和川菜都要吃到。预算 8000 元。',
      'Leaving Shanghai on November 19, 2 people: 2 days in Chengdu first, then 2 days in Chongqing, back to Shanghai from Chongqing on the 22nd. We want both hotpot and Sichuan food. Budget ¥8000.',
    ),
    origin: L('上海', 'Shanghai'),
    stops: [
      { city: L('成都', 'Chengdu'), days: 2 },
      { city: L('重庆', 'Chongqing'), days: 2 },
    ],
    startDate: '2026-11-19',
    people: 2,
    budget: 8000,
    prefs: { cuisines: L(['火锅', '川菜'], ['hotpot', 'Sichuan']) },
    feasible: true,
  }),
  t({
    id: 'hz-xm',
    title: L('两城联游：杭州 → 厦门', 'Two cities: Hangzhou → Xiamen'),
    core: false,
    request: L(
      '11 月 26 日从上海出发，我们 2 个人先去杭州玩 2 天，然后去厦门玩 2 天，29 日从厦门回上海。预算 7000 元。',
      'Leaving Shanghai on November 26, two of us: 2 days in Hangzhou first, then 2 days in Xiamen, back to Shanghai from Xiamen on the 29th. Budget ¥7000.',
    ),
    origin: L('上海', 'Shanghai'),
    stops: [
      { city: L('杭州', 'Hangzhou'), days: 2 },
      { city: L('厦门', 'Xiamen'), days: 2 },
    ],
    startDate: '2026-11-26',
    people: 2,
    budget: 7000,
    prefs: {},
    feasible: true,
  }),
  t({
    id: 'bj-veg',
    title: L('北京 3 天：素食', 'Beijing, 3 days: vegetarian'),
    core: false,
    request: L(
      '11 月 5 日到 7 日，2 个人从上海去北京，7 日回上海。我们想尝尝北京的素菜，行程里至少安排一顿素食餐厅。预算 7000 元。',
      "November 5 to 7, 2 people from Shanghai to Beijing, back to Shanghai on the 7th. We'd like to try Beijing's vegetarian cooking, so please include at least one meal at a vegetarian restaurant. Budget ¥7000.",
    ),
    origin: L('上海', 'Shanghai'),
    stops: [{ city: L('北京', 'Beijing'), days: 3 }],
    startDate: '2026-11-05',
    people: 2,
    budget: 7000,
    prefs: { cuisines: L(['素食'], ['vegetarian']) },
    feasible: true,
  }),
  t({
    id: 'sh-benbang',
    title: L('上海 3 天：4 人 + 本帮菜', 'Shanghai, 3 days: 4 people + Shanghainese food'),
    core: false,
    request: L(
      '11 月 12 日到 14 日，我们 4 个朋友从北京去上海玩 3 天，14 日回北京。想吃本帮菜。预算 10000 元。',
      'November 12 to 14, four friends from Beijing to Shanghai for 3 days, back to Beijing on the 14th. We want Shanghainese food. Budget ¥10000.',
    ),
    origin: L('北京', 'Beijing'),
    stops: [{ city: L('上海', 'Shanghai'), days: 3 }],
    startDate: '2026-11-12',
    people: 4,
    budget: 10000,
    prefs: { cuisines: L(['本帮菜'], ['Shanghainese']) },
    feasible: true,
  }),
  t({
    id: 'gz-cq-solo',
    title: L('重庆 2 天：精打细算', 'Chongqing, 2 days: every yuan counts'),
    core: false,
    request: L(
      '11 月 23 日、24 日，我一个人从广州去重庆，24 日回广州。预算只有 1500 元。',
      'November 23 and 24, just me, Guangzhou to Chongqing, back to Guangzhou on the 24th. My budget is only ¥1500.',
    ),
    origin: L('广州', 'Guangzhou'),
    stops: [{ city: L('重庆', 'Chongqing'), days: 2 }],
    startDate: '2026-11-23',
    people: 1,
    budget: 1500,
    prefs: {},
    feasible: true,
  }),
  t({
    id: 'xm-pet',
    title: L('厦门 3 天：带狗看海', 'Xiamen, 3 days: seaside with the dog'),
    core: false,
    request: L(
      '11 月 27 日到 29 日，我们 2 个人带着狗从上海去厦门玩 3 天，29 日回上海。预算 5000 元。',
      'November 27 to 29, two of us are taking our dog from Shanghai to Xiamen for 3 days, back to Shanghai on the 29th. Budget ¥5000.',
    ),
    origin: L('上海', 'Shanghai'),
    stops: [{ city: L('厦门', 'Xiamen'), days: 3 }],
    startDate: '2026-11-27',
    people: 2,
    budget: 5000,
    prefs: { pets: true },
    feasible: true,
  }),
  t({
    id: 'cd-slow',
    title: L('成都 4 天：每天一个景点 + 川菜素食', 'Chengdu, 4 days: one attraction a day + Sichuan and vegetarian'),
    core: false,
    request: L(
      '11 月 8 日到 11 日，2 个人从北京去成都，11 日回北京。节奏放慢，每天最多 1 个景点。想吃川菜，也想吃一次素斋。预算 9000 元。',
      'November 8 to 11, 2 people from Beijing to Chengdu, back to Beijing on the 11th. A slow pace, at most 1 attraction a day. We want Sichuan food, and one vegetarian temple meal too. Budget ¥9000.',
    ),
    origin: L('北京', 'Beijing'),
    stops: [{ city: L('成都', 'Chengdu'), days: 4 }],
    startDate: '2026-11-08',
    people: 2,
    budget: 9000,
    prefs: { maxAttractionsPerDay: 1, cuisines: L(['川菜', '素食'], ['Sichuan', 'vegetarian']) },
    feasible: true,
  }),
  t({
    id: 'gz-low-budget',
    title: L('四人去广州预算太低（不可行）', 'Four people to Guangzhou on too small a budget (infeasible)'),
    core: false,
    request: L(
      '11 月 6 日到 8 日，我们 4 个人从北京去广州玩 3 天，8 日回北京。预算 3000 元。',
      'November 6 to 8, four of us from Beijing to Guangzhou for 3 days, back to Beijing on the 8th. Budget ¥3000.',
    ),
    origin: L('北京', 'Beijing'),
    stops: [{ city: L('广州', 'Guangzhou'), days: 3 }],
    startDate: '2026-11-06',
    people: 4,
    budget: 3000,
    prefs: {},
    feasible: false,
    infeasibleWords: L(['预算'], ['budget']),
    infeasibleWhy: L('4 人往返北京—广州最便宜的交通就要 6896 元，远超 3000 元的预算', 'the cheapest round trip Beijing–Guangzhou for 4 people already costs ¥6896, far more than the ¥3000 budget'),
  }),
  t({
    id: 'hz-accessible-family',
    title: L('杭州 3 天：4 人 + 无障碍', 'Hangzhou, 3 days: 4 people + accessible'),
    core: false,
    request: L(
      '11 月 18 日到 20 日，我们一家 4 口从北京去杭州，20 日回北京。奶奶坐轮椅，酒店和景点都要无障碍。预算 9000 元。',
      'November 18 to 20, our family of 4 from Beijing to Hangzhou, back to Beijing on the 20th. Grandma uses a wheelchair, so the hotel and the sights all need to be accessible. Budget ¥9000.',
    ),
    origin: L('北京', 'Beijing'),
    stops: [{ city: L('杭州', 'Hangzhou'), days: 3 }],
    startDate: '2026-11-18',
    people: 4,
    budget: 9000,
    prefs: { accessible: true },
    feasible: true,
  }),
]

export function toTasks(): ProjectTask<TravelEnv, TravelPlan>[] {
  return TRAVEL_TASKS.map((spec) => ({
    id: spec.id,
    title: spec.title,
    core: spec.core,
    input: spec.request,
    check: ({ output }) => checkTravel(spec, output),
  }))
}
